name: SmartNinja CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install pip-audit
      run: pip install pip-audit

    # Code Quality Checks
    - name: Run Pylint
      run: |
        pylint --rcfile=.pylintrc app/ --output-format=text --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" || true

    # Security Scanning
    - name: Run Bandit security scan
      run: |
        bandit -r app/ -c bandit.yaml -f json --exit-zero || true
      # Using --exit-zero to prevent CI failure, but log issues

    - name: Check dependencies for vulnerabilities
      run: |
        pip-audit -r requirements.txt --strict || true
      # Using || true to log vulnerabilities but continue the workflow

    # Tests and Coverage
    - name: Run tests
      run: pytest --cov=app --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
